spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  messages:
    basename: errors

  servlet:
    multipart:
      max-file-size: 10485760

server:
  servlet:
    session:
      tracking-modes: cookie
#    context-path: /lilac



mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/*.xml

thread:
  pool:
    size: 5

