spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # mysql ver8 이상 com.mysql.cj.jdbc.Driver
    # 이하 com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_lilac_boot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_lilac_boot_dev
    password: 1234

logging:
  file:
    path: C:\lilac-web-log
  level:
    root: info
    com.steelrain.springboot.lilac: debug