-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 14:17:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_lilac_boot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_lilac_boot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_lilac_boot` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_lilac_boot` ;

-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_youtube_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_youtube_channel` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_youtube_channel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `c_id` VARCHAR(50) NULL,
  `title` VARCHAR(100) NULL,
  `desc` VARCHAR(1000) NULL,
  `publish_date` DATETIME NULL,
  `view_count` BIGINT UNSIGNED NULL,
  `subscriber_count` BIGINT UNSIGNED NULL COMMENT '구독자수',
  `subscriber_count_hidden` TINYINT(1) NULL DEFAULT 0 COMMENT '구독자수 비공개 여부',
  `video_count` BIGINT UNSIGNED NULL,
  `branding_keywords` VARCHAR(255) NULL COMMENT '채널에 등록한 채널 관련 키워드 \n예) 정보처리기사 정보처리산업기사 컴활1급 컴활2급 컴퓨터활용능력1급 컴퓨터활용능력2급 \\\"정보처리기사 필기\\\" \\\"정보처리기사 실기\\\" \\\"정보처리산업기사 필기\\\" \\\"정보처리산업기사 실기\\\" 사무자동화산업기사',
  `thumbnail_medium` VARCHAR(255) NULL,
  `thumbnail_high` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_youtube_playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_youtube_playlist` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_youtube_playlist` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `playlist_id` VARCHAR(50) NULL,
  `title` VARCHAR(100) NULL,
  `publish_date` DATETIME NULL,
  `thumbnail_medium` VARCHAR(255) NULL,
  `thumbnail_high` VARCHAR(255) NULL,
  `item_count` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_youtube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_youtube` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_youtube` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `channel_id` BIGINT NOT NULL,
  `youtube_playlist_id` BIGINT NULL,
  `video_id` VARCHAR(30) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `desc` VARCHAR(5000) NULL,
  `publish_date` DATETIME NULL,
  `fetch_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `thumbnail_medium` VARCHAR(255) NULL,
  `thumbnail_high` VARCHAR(255) NULL,
  `view_count` BIGINT NULL DEFAULT 0,
  `search_count` INT NULL DEFAULT 0,
  `playlist_id` VARCHAR(30) NULL,
  `like_count` BIGINT NULL,
  `favorite_count` BIGINT NULL,
  `comment_count` BIGINT NULL,
  `duration` VARCHAR(40) NULL,
  `score` DOUBLE NULL,
  `magnitude` DOUBLE NULL,
  FULLTEXT INDEX `title_idx` (`title`) INVISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `video_id_idx` (`video_id` ASC) VISIBLE,
  INDEX `fk_tbl_youtube_tbl_youtube_channel1_idx` (`channel_id` ASC) VISIBLE,
  INDEX `fk_tbl_youtube_tbl_playlist1_idx` (`youtube_playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_youtube_tbl_youtube_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `db_lilac_boot`.`tbl_youtube_channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_youtube_tbl_playlist1`
    FOREIGN KEY (`youtube_playlist_id`)
    REFERENCES `db_lilac_boot`.`tbl_youtube_playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_recommended_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_recommended_video` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_recommended_video` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `youtube_id` VARCHAR(30) NOT NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `youtube_id`),
  INDEX `fk_tbl_recommended_video_tbl_youtube_idx` (`youtube_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_recommended_video_tbl_youtube`
    FOREIGN KEY (`youtube_id`)
    REFERENCES `db_lilac_boot`.`tbl_youtube` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tnl_youtube_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tnl_youtube_comment` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tnl_youtube_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment_id` VARCHAR(30) NULL,
  `total_reply_count` BIGINT NULL,
  `author_display_name` VARCHAR(100) NULL,
  `text_original` VARCHAR(10000) NULL,
  `publish_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `reply_count` INT NULL DEFAULT 0,
  `channel_id` BIGINT NOT NULL,
  `youtube_id` BIGINT NOT NULL,
  `parent_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tnl_youtube_comment_tbl_youtube_channel1_idx` (`channel_id` ASC) VISIBLE,
  INDEX `fk_tnl_youtube_comment_tbl_youtube1_idx` (`youtube_id` ASC) VISIBLE,
  INDEX `fk_tnl_youtube_comment_tnl_youtube_comment1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_tnl_youtube_comment_tbl_youtube_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `db_lilac_boot`.`tbl_youtube_channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tnl_youtube_comment_tbl_youtube1`
    FOREIGN KEY (`youtube_id`)
    REFERENCES `db_lilac_boot`.`tbl_youtube` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tnl_youtube_comment_tnl_youtube_comment1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `db_lilac_boot`.`tnl_youtube_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_subject` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_subject` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_member` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_member` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(20) NULL,
  `description` VARCHAR(500) NULL,
  `region` CHAR(2) NULL,
  `dtl_region` CHAR(5) NULL,
  `profile_original` VARCHAR(255) NULL,
  `profile_save` VARCHAR(255) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `grade` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_license` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_license` (
  `code` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `schedule_json` JSON NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_lecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_lecture` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_lecture` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `member_id` BIGINT NOT NULL,
  `subject_id` BIGINT NOT NULL,
  `license_code` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `description` VARCHAR(500) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `progress` INT NULL,
  PRIMARY KEY (`id`, `member_id`),
  INDEX `fk_tbl_lecture_tbl_member1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_tbl_lecture_tbl_subject1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_tbl_lecture_tbl_license1_idx` (`license_code` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_lecture_tbl_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_lilac_boot`.`tbl_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_lecture_tbl_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `db_lilac_boot`.`tbl_subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_lecture_tbl_license1`
    FOREIGN KEY (`license_code`)
    REFERENCES `db_lilac_boot`.`tbl_license` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`ref_tbl_lecture_youtube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`ref_tbl_lecture_youtube` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`ref_tbl_lecture_youtube` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `lecture_id` BIGINT NOT NULL,
  `lecture_member_id` BIGINT NOT NULL,
  `youtube_id` BIGINT NOT NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_ref_tbl_lecture_youtube_tbl_lecture1_idx` (`lecture_id` ASC, `lecture_member_id` ASC) VISIBLE,
  INDEX `fk_ref_tbl_lecture_youtube_tbl_youtube1_idx` (`youtube_id` ASC) VISIBLE,
  CONSTRAINT `fk_ref_tbl_lecture_youtube_tbl_lecture1`
    FOREIGN KEY (`lecture_id` , `lecture_member_id`)
    REFERENCES `db_lilac_boot`.`tbl_lecture` (`id` , `member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_tbl_lecture_youtube_tbl_youtube1`
    FOREIGN KEY (`youtube_id`)
    REFERENCES `db_lilac_boot`.`tbl_youtube` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_book` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_book` (
  `isbn13` CHAR(13) NOT NULL,
  `title` VARCHAR(100) NULL,
  `contents` VARCHAR(500) NULL,
  `url` VARCHAR(255) NULL,
  `publish_date` DATETIME NULL,
  `authors` VARCHAR(50) NULL,
  `publisher` VARCHAR(100) NULL,
  `translators` VARCHAR(100) NULL,
  `price` INT NULL,
  `sale_price` INT NULL,
  `thumbnail` VARCHAR(100) NULL,
  `status` VARCHAR(10) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`isbn13`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_library` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_library` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `lib_code` CHAR(6) NULL,
  `name` VARCHAR(100) NULL,
  `address` VARCHAR(100) NULL,
  `tel` VARCHAR(20) NULL,
  `fax` VARCHAR(20) NULL,
  `latitude` CHAR(10) NULL,
  `longitude` CHAR(10) NULL,
  `homepage` VARCHAR(255) NULL,
  `closed` VARCHAR(255) NULL,
  `operating_time` VARCHAR(50) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `isbn13` CHAR(13) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_library_tbl_book1_idx` (`isbn13` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_library_tbl_book1`
    FOREIGN KEY (`isbn13`)
    REFERENCES `db_lilac_boot`.`tbl_book` (`isbn13`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`ref_tbl_lecture_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`ref_tbl_lecture_book` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`ref_tbl_lecture_book` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `lecture_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  `isbn13` CHAR(13) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ref_lecture_book_tbl_lecture1_idx` (`lecture_id` ASC, `member_id` ASC) VISIBLE,
  INDEX `fk_ref_lecture_book_tbl_book1_idx` (`isbn13` ASC) VISIBLE,
  CONSTRAINT `fk_ref_lecture_book_tbl_lecture1`
    FOREIGN KEY (`lecture_id` , `member_id`)
    REFERENCES `db_lilac_boot`.`tbl_lecture` (`id` , `member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_lecture_book_tbl_book1`
    FOREIGN KEY (`isbn13`)
    REFERENCES `db_lilac_boot`.`tbl_book` (`isbn13`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_freeboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_freeboard` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_freeboard` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `contents` VARCHAR(2000) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `hits` INT NULL,
  `attached_file` TINYINT NULL,
  `like_count` INT NULL,
  `member_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `member_id`),
  INDEX `fk_tbl_freeboard_tbl_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_freeboard_tbl_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_lilac_boot`.`tbl_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_recommened_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_recommened_book` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_recommened_book` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tbl_book_isbn13` CHAR(13) NOT NULL,
  PRIMARY KEY (`id`, `tbl_book_isbn13`),
  INDEX `fk_tbl_recommened_book_tbl_book1_idx` (`tbl_book_isbn13` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_recommened_book_tbl_book1`
    FOREIGN KEY (`tbl_book_isbn13`)
    REFERENCES `db_lilac_boot`.`tbl_book` (`isbn13`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_attached_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_attached_file` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_attached_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `original_file` VARCHAR(100) NULL,
  `stored_file` VARCHAR(100) NULL,
  `freeboard_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `freeboard_id`),
  INDEX `fk_tbl_attached_file_tbl_freeboard1_idx` (`freeboard_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_attached_file_tbl_freeboard1`
    FOREIGN KEY (`freeboard_id`)
    REFERENCES `db_lilac_boot`.`tbl_freeboard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_freeboard_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_freeboard_comment` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_freeboard_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `contents` VARCHAR(1000) NULL,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `freeboard_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  `parent_id` BIGINT NULL,
  PRIMARY KEY (`id`, `freeboard_id`, `member_id`),
  INDEX `fk_tbl_freeboard_comment_tbl_freeboard_comment1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_tbl_freeboard_comment_tbl_freeboard1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_freeboard_comment_tbl_freeboard_comment1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `db_lilac_boot`.`tbl_freeboard_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_freeboard_comment_tbl_freeboard1`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_lilac_boot`.`tbl_freeboard` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_youtube_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_youtube_like` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_youtube_like` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `like_idx` INT NULL,
  `youtube_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `youtube_id`, `member_id`),
  INDEX `fk_tbl_youtube_like_tbl_youtube1_idx` (`youtube_id` ASC) VISIBLE,
  INDEX `fk_tbl_youtube_like_tbl_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_youtube_like_tbl_youtube1`
    FOREIGN KEY (`youtube_id`)
    REFERENCES `db_lilac_boot`.`tbl_youtube` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_youtube_like_tbl_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_lilac_boot`.`tbl_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_freeboard_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_freeboard_like` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_freeboard_like` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `like_idx` INT NULL,
  `freeboard_id` BIGINT NOT NULL,
  `member_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `freeboard_id`, `member_id`),
  INDEX `fk_tbl_freeboard_like_tbl_freeboard1_idx` (`freeboard_id` ASC, `member_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_freeboard_like_tbl_freeboard1`
    FOREIGN KEY (`freeboard_id` , `member_id`)
    REFERENCES `db_lilac_boot`.`tbl_freeboard` (`id` , `member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lilac_boot`.`tbl_comment_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lilac_boot`.`tbl_comment_like` ;

CREATE TABLE IF NOT EXISTS `db_lilac_boot`.`tbl_comment_like` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reg_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `like_idx` INT NULL,
  `comment_id` BIGINT NOT NULL,
  `freeboard_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `comment_id`, `freeboard_id`),
  INDEX `fk_tbl_comment_like_tbl_freeboard_comment1_idx` (`comment_id` ASC, `freeboard_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_comment_like_tbl_freeboard_comment1`
    FOREIGN KEY (`comment_id` , `freeboard_id`)
    REFERENCES `db_lilac_boot`.`tbl_freeboard_comment` (`id` , `freeboard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
